import { Template } from "./types";

export const presetTemplates: Template[] = [
  {
    id: "preset-website-audit",
    name: "Website QA Audit",
    isPreset: true,
    state: {
      taskMode: "analyze",
      role: "a senior QA engineer who has tested 200+ high-converting websites and understands user behavior deeply",
      taskDescription: "Open [WEBSITE_URL] and test the full first-time visitor experience from landing to key action (signup, purchase, or contact). Click through every major path a new user would take. Document all states including loading, errors, empty states, and success confirmations. Identify broken links, unclickable elements, missing feedback, and confusing navigation. Highlight where users might drop off or lose trust.",
      context: "",
      tone: "Technical",
      outputFormat: "Table",
      length: "Detailed",
      audience: "Expert",
      extras: ["Be critical / honest", "Actionable output"],
      avoid: "",
    },
  },
  {
    id: "preset-form-testing",
    name: "Form Edge Case Breaker",
    isPreset: true,
    state: {
      taskMode: "debug",
      role: "a QA engineer specializing in web form validation and UX optimization",
      taskDescription: "Open [WEBSITE_URL] and locate all forms (contact, signup, checkout, etc.). Test each form with empty fields, extremely long inputs (500+ characters), special characters, and invalid formats (incorrect emails, phone numbers with letters). Observe how the system responds. Flag silent failures, weak validation, or unclear error messages. Ensure success states provide clear feedback.",
      context: "",
      tone: "Technical",
      outputFormat: "Step-by-Step",
      length: "Detailed",
      audience: "Expert",
      extras: ["Think step-by-step", "Be critical / honest"],
      avoid: "",
    },
  },
  {
    id: "preset-code-review",
    name: "Code Review",
    isPreset: true,
    state: {
      taskMode: "analyze",
      role: "a principal engineer conducting a thorough code review focused on correctness, security, and maintainability",
      taskDescription: "",
      context: "",
      tone: "Technical",
      outputFormat: "Markdown",
      length: "Detailed",
      audience: "Expert",
      extras: ["Be critical / honest", "Include code snippets", "Suggest alternatives"],
      avoid: "",
    },
  },
  {
    id: "preset-eli5",
    name: "Explain Like I'm 5",
    isPreset: true,
    state: {
      taskMode: "learn",
      role: "a patient teacher who makes complex topics simple using everyday analogies",
      taskDescription: "",
      context: "",
      tone: "Friendly",
      outputFormat: "Paragraphs",
      length: "Medium",
      audience: "Beginner",
      extras: ["Include examples", "No filler / no fluff"],
      avoid: "",
    },
  },
  {
    id: "preset-quick-draft",
    name: "Quick Draft",
    isPreset: true,
    state: {
      taskMode: "write",
      role: "",
      taskDescription: "",
      context: "",
      tone: "Casual",
      outputFormat: "Paragraphs",
      length: "Brief",
      audience: "Mixed",
      extras: ["Actionable output"],
      avoid: "",
    },
  },
  {
    id: "preset-architecture",
    name: "Architecture Plan",
    isPreset: true,
    state: {
      taskMode: "brainstorm",
      role: "a solutions architect with experience scaling systems to millions of users",
      taskDescription: "",
      context: "",
      tone: "Professional",
      outputFormat: "Markdown",
      length: "Comprehensive",
      audience: "Expert",
      extras: ["Compare approaches", "Pros & cons"],
      avoid: "",
    },
  },
  {
    id: "preset-bug-fix",
    name: "Bug Report Fix",
    isPreset: true,
    state: {
      taskMode: "debug",
      role: "",
      taskDescription: "",
      context: "",
      tone: "Technical",
      outputFormat: "Step-by-Step",
      length: "Detailed",
      audience: "Intermediate",
      extras: ["Think step-by-step", "Include code snippets"],
      avoid: "",
    },
  },
  {
    id: "preset-email",
    name: "Email Drafter",
    isPreset: true,
    state: {
      taskMode: "write",
      role: "a professional business writer who crafts concise, effective emails that get responses",
      taskDescription: "",
      context: "",
      tone: "Professional",
      outputFormat: "Paragraphs",
      length: "Brief",
      audience: "Mixed",
      extras: ["No filler / no fluff", "Actionable output"],
      avoid: "",
    },
  },
  {
    id: "preset-marketing",
    name: "Marketing Copy",
    isPreset: true,
    state: {
      taskMode: "write",
      role: "a conversion copywriter who writes compelling, benefit-focused copy that drives action",
      taskDescription: "",
      context: "",
      tone: "Creative",
      outputFormat: "Paragraphs",
      length: "Medium",
      audience: "Mixed",
      extras: ["Include examples", "Actionable output"],
      avoid: "",
    },
  },
  {
    id: "preset-api-review",
    name: "API Design Review",
    isPreset: true,
    state: {
      taskMode: "analyze",
      role: "a senior API designer who reviews for REST best practices, security, and developer experience",
      taskDescription: "",
      context: "",
      tone: "Technical",
      outputFormat: "Markdown",
      length: "Detailed",
      audience: "Expert",
      extras: ["Be critical / honest", "Suggest alternatives", "Compare approaches"],
      avoid: "",
    },
  },
  {
    id: "preset-meeting-summary",
    name: "Meeting Summary",
    isPreset: true,
    state: {
      taskMode: "write",
      role: "an executive assistant who writes clear, actionable meeting summaries with crisp next steps",
      taskDescription: "Summarize the following meeting notes into a structured summary with key decisions, action items, and owners: [PASTE NOTES]",
      context: "",
      tone: "Professional",
      outputFormat: "Bullet Points",
      length: "Brief",
      audience: "Mixed",
      extras: ["Actionable output", "No filler / no fluff"],
      avoid: "",
    },
  },
  {
    id: "preset-perf-review",
    name: "Performance Review",
    isPreset: true,
    state: {
      taskMode: "write",
      role: "an HR professional who writes balanced, growth-focused performance reviews",
      taskDescription: "",
      context: "",
      tone: "Professional",
      outputFormat: "Paragraphs",
      length: "Detailed",
      audience: "Mixed",
      extras: ["Be critical / honest", "Actionable output"],
      avoid: "",
    },
  },
  {
    id: "preset-sql",
    name: "SQL Query Builder",
    isPreset: true,
    state: {
      taskMode: "code",
      role: "a database engineer who writes optimized, secure SQL queries with clear explanations",
      taskDescription: "",
      context: "",
      tone: "Technical",
      outputFormat: "Code Block",
      length: "Detailed",
      audience: "Intermediate",
      extras: ["Include examples", "Include code snippets", "Think step-by-step"],
      avoid: "",
    },
  },
  {
    id: "preset-product-spec",
    name: "Product Spec Writer",
    isPreset: true,
    state: {
      taskMode: "write",
      role: "a senior product manager who writes clear, complete product requirement documents",
      taskDescription: "",
      context: "",
      tone: "Professional",
      outputFormat: "Markdown",
      length: "Comprehensive",
      audience: "Mixed",
      extras: ["Include examples", "Actionable output", "Compare approaches"],
      avoid: "",
    },
  },
  {
    id: "preset-startup-pitch",
    name: "Startup Pitch",
    isPreset: true,
    state: {
      taskMode: "brainstorm",
      role: "a startup advisor who has helped dozens of companies craft compelling investor narratives",
      taskDescription: "",
      context: "",
      tone: "Professional",
      outputFormat: "Markdown",
      length: "Detailed",
      audience: "Expert",
      extras: ["Pros & cons", "Be critical / honest", "Actionable output"],
      avoid: "",
    },
  },
];
